Repository Exiv2/exiv2, pull requests merged in 2019-10, with the labels that each got.

#989 Fix 987 (taglist.cpp changes)
  CMakeLists.txt
  README-SAMPLES.md
  man/man1/exiv2.1
  samples/taglist.cpp
  src/CMakeLists.txt
  tests/bugfixes/github/test_issue_987.py
  tests/suite.conf
Labels: documentation, samples, to-master

#1013 Fix #1011 fix_1011_jp2_readmetadata_loop
  src/jp2image.cpp
  test/data/Jp2Image_readMetadata_loop.poc
  tests/bugfixes/github/test_CVE_2017_17725.py
  tests/bugfixes/github/test_issue_1011.py
Labels: to-master

#977 Add XMP Initialisation/Cleanup code to every main()
  README.md
  samples/conntest.cpp
  samples/convert-test.cpp
  samples/easyaccess-test.cpp
  samples/exifcomment.cpp
  samples/exifdata-test.cpp
  samples/exifdata.cpp
  samples/exifprint.cpp
  samples/exifvalue.cpp
  samples/exiv2json.cpp
  samples/geotag.cpp
  samples/getopt-test.cpp
  samples/httptest.cpp
  samples/ini-test.cpp
  samples/iotest.cpp
  samples/iptceasy.cpp
  samples/iptcprint.cpp
  samples/iptctest.cpp
  samples/key-test.cpp
  samples/largeiptc-test.cpp
  samples/metacopy.cpp
  samples/mmap-test.cpp
  samples/mrwthumb.cpp
  samples/mt-test.cpp
  samples/path-test.cpp
  samples/prevtest.cpp
  samples/remotetest.cpp
  samples/stringto-test.cpp
  samples/taglist.cpp
  samples/tiff-test.cpp
  samples/tiffaddpath-test.cpp
  samples/toexv.cpp
  samples/werror-test.cpp
  samples/write-test.cpp
  samples/write2-test.cpp
  samples/xmpdump.cpp
  samples/xmpparse.cpp
  samples/xmpparser-test.cpp
  samples/xmpprint.cpp
  samples/xmpsample.cpp
  src/exiv2.cpp
Labels: to-master

#1020 crwimage: Check offset and size against total size
  src/crwimage_int.cpp
  test/data/POC-file_issue_1019
  tests/bugfixes/github/test_issue_1019.py
  tests/suite.conf
Labels: backport-to-0.27

#1006 fix_958_usr_bin_env_bash_test
  .gitignore
  test/addmoddel.sh
  test/bugfixes-test.sh
  test/conversions.sh
  test/crw-test.sh
  test/curliotest.sh
  test/eps-preview-test.sh
  test/eps-test.sh
  test/exifdata-test.sh
  test/exiv2-test.sh
  test/geotag-test.sh
  test/http-test.sh
  test/httpiotest.sh
  test/icc-test.sh
  test/imagetest.sh
  test/iotest.sh
  test/iptctest.sh
  test/iso65k-test.sh
  test/modify-test.sh
  test/path-test.sh
  test/preview-test.sh
  test/sshiotest.sh
  test/stdin-test.sh
  test/stringto-test.sh
  test/testMSVC.sh
  test/version-test.sh
  test/video-test.sh
  test/webp-test.sh
  test/write-test.sh
  test/write-video-test.sh
  test/write2-test.sh
  test/xmpparser-test.sh
Labels: testing, to-master

#1007 fix_910_remote_io_block+1
  src/basicio.cpp
Labels: to-master

#1005 fix_1004_lens_exiftool_compatibility
  src/canonmn_int.cpp
  test/data/exiv2-test.out
  tests/bugfixes/redmine/test_issue_1252.py
Labels: Lens, to-master

#1025 027 fix warnings
  .travis.yml
  cmake/compilerFlags.cmake
  cmake/compilerFlagsExiv2.cmake
  cmake/printSummary.cmake
  src/actions.cpp
  src/jpgimage.cpp
Labels: Compilers, to-master

#1032 Fixes #1014 Two Nikon lenses still not detected
  README.md
  test/data/exiv2-bug1014.exv
  test/data/exiv2-bug1014_2.exv
  tests/bugfixes/github/test_issue_1014.py
Labels: backport-to-0.27
