Repository Exiv2/exiv2, pull requests merged in 2019-07, with the labels that each got.

#941 Tidy/exiv2 app
  include/exiv2/config.h
  src/actions.cpp
  src/actions.hpp
  src/basicio.cpp
  src/exif.cpp
  src/exiv2.cpp
  src/params.cpp
  src/params.hpp
  src/utils.cpp
  src/utils.hpp
Labels: Refactoring

#946 mrwimage bounds checking
  src/mrwimage.cpp
  test/data/issue_943_poc1.mrm
  test/data/issue_943_poc2.mrm
  tests/bugfixes/github/test_issue_943.py
Labels: bug, to-master

#939 Replace DEBUG with EXIV2_DEBUG_MESSAGES
  README.md
  samples/geotag.cpp
  src/actions.cpp
  src/basicio.cpp
  src/bmpimage.cpp
  src/convert.cpp
  src/cr2image.cpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/gifimage.cpp
  src/iptc.cpp
  src/jp2image.cpp
  src/jpgimage.cpp
  src/mrwimage.cpp
  src/orfimage.cpp
  src/params.cpp
  src/pgfimage.cpp
  src/pngchunk_int.cpp
  src/pngimage.cpp
  src/properties.cpp
  src/psdimage.cpp
  src/rafimage.cpp
  src/rw2image.cpp
  src/tgaimage.cpp
  src/tiffcomposite_int.cpp
  src/tiffimage.cpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  src/webpimage.cpp
  src/xmp.cpp
  src/xmpsidecar.cpp
Labels: Compilers

#949 Add Dutch translation of Exiv2
  po/CMakeLists.txt
  po/nl.po
Labels: backport-to-0.27

#938 Replace DEBUG with EXIV2_DEBUG_MESSAGES
  README.md
  samples/geotag.cpp
  src/actions.cpp
  src/basicio.cpp
  src/bmpimage.cpp
  src/convert.cpp
  src/cr2image.cpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/gifimage.cpp
  src/iptc.cpp
  src/jp2image.cpp
  src/jpgimage.cpp
  src/mrwimage.cpp
  src/orfimage.cpp
  src/pgfimage.cpp
  src/pngchunk_int.cpp
  src/pngimage.cpp
  src/properties.cpp
  src/psdimage.cpp
  src/rafimage.cpp
  src/rw2image.cpp
  src/tgaimage.cpp
  src/tiffcomposite_int.cpp
  src/tiffimage.cpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  src/webpimage.cpp
  src/xmp.cpp
  src/xmpsidecar.cpp
Labels: Compilers

#955 Conan update
  appveyor.yml
  ci/install.sh
  conanfile.py
  src/CMakeLists.txt
Labels: to-master

#944 Add bounds check to MemIo::seek().
  src/basicio.cpp
  unitTests/CMakeLists.txt
  unitTests/test_basicio.cpp
Labels: backport-to-0.27

#962 Fix integer overflow in WebPImage::getHeaderOffset
  src/webpimage.cpp
  test/data/issue_960.poc.webp
  tests/bugfixes/github/test_issue_960.py
Labels: bug, to-master

#968 027 update conan
  appveyor.yml
  ci/install.sh
  conanfile.py
Labels: to-master

#967 fix_966_macosx_libintl_mono_framework
  CMakeLists.txt
  README.md
  appveyor.yml
  cmake/findDependencies.cmake
Labels: to-master
