Repository Exiv2/exiv2, pull requests merged in 2019-02, with the labels that each got.

#676 fix section links in conan readme
  README-CONAN.md
Labels: backport-to-0.27

#682 Fix resource leaks
  src/http.cpp
Labels: backport-to-0.27

#686 Correct the name of the Archlinux container on Dockerhub
  .gitlab-ci.yml
  ci/install_dependencies.sh
Labels: backport-to-0.27

#700 exiv2-xmp linked privately
  samples/CMakeLists.txt
  src/CMakeLists.txt
Labels: CMake, to-master

#705 Run upgrade in Archlinux container
  ci/install_dependencies.sh
Labels: backport-to-0.27

#706 Fix access to null pointer in TiffParser
  src/tiffimage_int.cpp
  test/data/tiffimage_int-out-of-bound-read-poc-2
  tests/bugfixes/github/test_issue_590.py
Labels: bug, to-master

#721 Add MinGW build to GitLab CI
  .gitlab-ci.yml
  ci/test_build.py
  src/futils.cpp
Labels: backport-to-0.27
