Repository Exiv2/exiv2, pull requests merged in 2019-04, with the labels that each got.

#771 travis: use newer xcode version and drop the old one
  .travis.yml
  ci/install.sh
  ci/run.sh
Labels: CI

#772 travis: use newer xcode version (fix build)
  .travis.yml
  ci/install.sh
  ci/run.sh
Labels: CI

#769 Move .clang-format to .clang-format.optional
  .clang-format.optional
  CODING_GUIDELINES.md
Labels: backport-to-0.27

#773 Fix #744
  src/jp2image.cpp
Labels: bug, to-master

#799 Fix #798
  README.md
  releasenotes/CYGWIN/ReadMe.txt
  releasenotes/Darwin/ReadMe.txt
  releasenotes/Linux/ReadMe.txt
  releasenotes/MinGW/ReadMe.txt
  releasenotes/msvc/ReadMe.txt
  src/CMakeLists.txt
Labels: to-master

#788 Refactor actions
  src/actions.cpp
  src/actions.hpp
  src/exiv2.cpp
Labels: Refactoring

#806 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation
