Repository Exiv2/exiv2, pull requests merged in 2019-06, with the labels that each got.

#889 fix662 Update man page to clarify rename overwrite
  src/exiv2.1
Labels: to-master

#909 DLL information depends now on proper definition
  src/version.cpp
Labels: enhancement, to-master

#900 fix646_NikonAF22
  src/makernote_int.cpp
  src/makernote_int.hpp
  src/nikonmn_int.cpp
  src/nikonmn_int.hpp
  src/tags_int.cpp
  src/tags_int.hpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  test/data/_DSC8437.exv
  tests/bugfixes/github/test_issue_646.py
Labels: to-master

#924 0.27: use libssh-config instead of custom FindSSH.cmake
  cmake/FindSSH.cmake
  cmake/findDependencies.cmake
  src/CMakeLists.txt
Labels: to-master

#921 Adding README-SAMPLES.md and removing exiv2samples.1
  README-SAMPLES.md
  samples/CMakeLists.txt
  samples/exiv2samples.1
  src/doxygen.hpp.in
Labels: documentation, to-master

#906 Fix 582 Add support for FocusPosition in Sony RAW files
  doc/templates/Makefile
  src/sonymn_int.cpp
  src/sonymn_int.hpp
  src/tags_int.cpp
  src/tags_int.hpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  test/data/exiv2-pr906.exv
  tests/bugfixes/github/test_pr_906.py
Labels: to-master

#928 Corrections to README.md 2.8.Localisation
  README.md
  po/CMakeLists.txt
Labels: to-master
