Repository Exiv2/exiv2, pull requests merged in 2019-05, with the labels that each got.

#815 Avoid null pointer exception due to NULL return value from strchr
  src/http.cpp
Labels: to-master

#822 Fix in sidecar files #589
  src/xmpsidecar.cpp
Labels: to-master

#795 Avoid negative integer overflow when iccOffset > chunkLength
  src/pngimage.cpp
  test/data/issue_790_poc2.png
  tests/bugfixes/github/test_issue_790.py
Labels: to-master

#821 CURL lib and include directories private for exiv2lib
  samples/CMakeLists.txt
  src/CMakeLists.txt
Labels: backport-to-0.27

#794 Avoid negative integer overflow when chunkLength == 0
  src/pngimage.cpp
  test/data/issue_789_poc1.png
  tests/bugfixes/github/test_issue_789.py
Labels: to-master

#829 Update Catalan translation
  po/ca.po
Labels: Translation, backport-to-0.27

#831 fix #818. Restore 0.25 behaviour of `$ exiv2 -g image ...`
  src/actions.cpp
  src/exiv2.1
  tests/bugfixes/github/test_issue_818.py
Labels: to-master

#844 Fix integer overflows in crwimage_int.cpp
  src/crwimage_int.cpp
  test/data/issue_843_poc.crw
  tests/bugfixes/github/test_issue_843.py
Labels: to-master

#840 Issue 839: add bounds check.
  src/preview.cpp
  test/data/issue_839_poc.rw2
  tests/bugfixes/github/test_issue_839.py
Labels: to-master

#842 Issue 841: replace assert with enforce.
  src/crwimage_int.cpp
  src/crwimage_int.hpp
  test/data/issue_841_poc.crw
  tests/bugfixes/github/test_issue_841.py
Labels: to-master

#852 Check bounds of month and day
  test/data/issue_851_poc.xmp
  tests/bugfixes/github/test_issue_851.py
  xmpsdk/src/XMPUtils.cpp
Labels: to-master

#854 Add bounds check on allocation size.
  src/jpgimage.cpp
  test/data/issue_853_poc.jpg
  tests/bugfixes/github/test_issue_853.py
Labels: to-master

#856 Add bounds check of resourceSize.
  src/psdimage.cpp
  test/data/issue_855_poc.psd
  tests/bugfixes/github/test_issue_855.py
Labels: to-master

#858 Check bounds of jpg_img_off and jpg_img_len
  src/rafimage.cpp
  test/data/issue_857_coverage.raf
  test/data/issue_857_poc.raf
  tests/bugfixes/github/test_issue_857.py
Labels: to-master

#862 Add better bounds checking in PngImage::printStructure()
  src/pngimage.cpp
  test/data/issue_828_poc.png
  tests/bugfixes/github/test_issue_828.py
Labels: to-master

#868 Prevent out-of-bounds read in IptcParser::decode()
  src/iptc.cpp
  test/data/issue_867_poc.psd
  tests/bugfixes/github/test_issue_867.py
Labels: to-master

#870 Remove call to atol, which might read off the end of the buffer.
  src/pngchunk_int.cpp
  test/data/issue_869_poc.png
  tests/bugfixes/github/test_issue_845.py
  tests/bugfixes/github/test_issue_869.py
Labels: to-master

#881 IO read/write functions with size_t (4)
  include/exiv2/basicio.hpp
  include/exiv2/exif.hpp
  include/exiv2/image.hpp
  include/exiv2/iptc.hpp
  include/exiv2/jpgimage.hpp
  include/exiv2/metadatum.hpp
  include/exiv2/preview.hpp
  include/exiv2/psdimage.hpp
  include/exiv2/tiffimage.hpp
  include/exiv2/types.hpp
  include/exiv2/value.hpp
  include/exiv2/webpimage.hpp
  include/exiv2/xmp_exiv2.hpp
  samples/iotest.cpp
  samples/tiff-test.cpp
  src/actions.cpp
  src/basicio.cpp
  src/bigtiffimage.cpp
  src/casiomn_int.cpp
  src/convert.cpp
  src/cr2header_int.cpp
  src/cr2header_int.hpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/image.cpp
  src/iptc.cpp
  src/jp2image.cpp
  src/jpgimage.cpp
  src/makernote_int.cpp
  src/makernote_int.hpp
  src/mrwimage.cpp
  src/orfimage_int.cpp
  src/orfimage_int.hpp
  src/pgfimage.cpp
  src/pngchunk_int.cpp
  src/pngchunk_int.hpp
  src/pngimage.cpp
  src/preview.cpp
  src/psdimage.cpp
  src/rafimage.cpp
  src/tgaimage.cpp
  src/tiffcomposite_int.cpp
  src/tiffcomposite_int.hpp
  src/tiffimage.cpp
  src/tiffimage_int.cpp
  src/tiffimage_int.hpp
  src/tiffvisitor_int.cpp
  src/tiffvisitor_int.hpp
  src/types.cpp
  src/value.cpp
  src/webpimage.cpp
  src/xmp.cpp
  src/xmpsidecar.cpp
Labels: Refactoring

#884 Add CTest support
  CMakeLists.txt
  README.md
  unitTests/CMakeLists.txt
Labels: CMake

#886 fix743_NikonSigmaArtLens
  src/nikonmn_int.cpp
  test/data/issue_743.exv
  tests/bugfixes/github/test_issue_743.py
Labels: to-master

#885 fix880_NikonEndian
  src/tiffimage_int.cpp
  test/data/exifdata-test.out
  test/data/exiv2-test.out
Labels: to-master

#891 Add Tamron SP 70-300mm f/4-5.6 Di VC USD (Model: A030) (Nikon Mount)
  src/nikonmn_int.cpp
  test/data/Tamron_SP70-300_F4-5.6_Di_VC_USD_A030.exv
  tests/bugfixes/github/test_issue_598.py
Labels: backport-to-0.27
