Repository Exiv2/exiv2, pull requests merged in 2019-03, with the labels that each got.

#722 Fix doxygen generation
  cmake/Doxyfile.in
  cmake/generateDoc.cmake
  doc/cmake_doc.sh
Labels: backport-to-0.27, documentation

#723 [CI] Fix name of the OpenSUSE Tumbleweed container for GitLab CI
  .gitlab-ci.yml
Labels: backport-to-0.27

#730 Replace check_function_exists by check_cxx_symbol_exist
  cmake/generateConfigFile.cmake
Labels: CMake, backport-to-0.27

#737 Enum class for image types
  include/exiv2/CMakeLists.txt
  include/exiv2/bigtiffimage.hpp
  include/exiv2/bmpimage.hpp
  include/exiv2/cr2image.hpp
  include/exiv2/crwimage.hpp
  include/exiv2/gifimage.hpp
  include/exiv2/image.hpp
  include/exiv2/image_types.hpp
  include/exiv2/jp2image.hpp
  include/exiv2/jpgimage.hpp
  include/exiv2/mrwimage.hpp
  include/exiv2/orfimage.hpp
  include/exiv2/pgfimage.hpp
  include/exiv2/pngimage.hpp
  include/exiv2/psdimage.hpp
  include/exiv2/rafimage.hpp
  include/exiv2/rw2image.hpp
  include/exiv2/tgaimage.hpp
  include/exiv2/tiffimage.hpp
  include/exiv2/types.hpp
  include/exiv2/webpimage.hpp
  include/exiv2/xmpsidecar.hpp
  src/actions.cpp
  src/basicio.cpp
  src/image.cpp
  src/jpgimage.cpp
  unitTests/CMakeLists.txt
  unitTests/test_ImageFactory.cpp
Labels: enhancement

#747 0.27 fix620
  contrib/organize/work/exiv2/contrib/organize/organize.cpp
Labels: to-master

#751 Enable support for msvc 2015
  src/crwimage_int.cpp
  src/makernote_int.cpp
Labels: CI

#749 Project cleanup
  samples/CMakeLists.txt
  samples/toexv.cpp
  samples/toexv.hpp
  src/CMakeLists.txt
  unitTests/CMakeLists.txt
  unitTests/gtestwrapper.h
  unitTests/mainTestRunner.cpp
  unitTests/test_DateValue.cpp
  unitTests/test_TimeValue.cpp
  unitTests/test_XmpKey.cpp
  unitTests/test_cr2header_int.cpp
  unitTests/test_enforce.cpp
  unitTests/test_futils.cpp
  unitTests/test_helper_functions.cpp
  unitTests/test_image_int.cpp
  unitTests/test_safe_op.cpp
  unitTests/test_slice.cpp
  unitTests/test_tiffheader.cpp
  unitTests/test_types.cpp
Labels: CMake

#753 Fix #742 - master
  src/jp2image.cpp
  test/data/issue_742_poc
  tests/bugfixes/github/test_issue_742.py
Labels: backport-to-0.27
