Repository Exiv2/exiv2, pull requests merged in 2021-05, with the labels that each got.

#1597 fix archlinux ci build
  .github/workflows/linux_distribution_check.yml
Labels: CI

#1606 Initialize field.
  src/actions.hpp
Labels: forward-to-main

#1627 Use readOrThrow to check error conditions of io.read()
  src/webpimage.cpp
Labels: forward-to-main

#1657 Fix quadratic complexity performance bug
  xmpsdk/src/XMPMeta-Parse.cpp
Labels: forward-to-main

#1687 Remove free() function from DataBuf
  include/exiv2/types.hpp
  src/image.cpp
  src/pngimage.cpp
  src/types.cpp
Labels: refactoring

#1676 feat: Setup github actions workflow to build tagged release and nightly pre-release
  .github/workflows/release.yml
Labels: CI, enhancement
