Repository Exiv2/exiv2, pull requests merged in 2021-04, with the labels that each got.

#1504 metacopy -x parameter not in optstring
  samples/metacopy.cpp
  samples/metacopy.hpp
Labels: samples

#1546 fix_ci_ubuntu18.4
  .travis.yml
Labels: CI

#1554 fix_enableBMFF_v1
  CMakeLists.txt
  README.md
  include/exiv2/bmffimage.hpp
  include/exiv2/exiv2.hpp
  src/CMakeLists.txt
  src/bmffimage.cpp
Labels: architecture
