Repository Exiv2/exiv2, pull requests merged in 2021-07, with the labels that each got.

#1758 Check that the iterator is not end() after calling findKey
  src/convert.cpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/iptc.cpp
  src/pentaxmn_int.cpp
  src/xmp.cpp
  test/data/issue_ghsa_h9x9_4f77_336w_poc.exv
  tests/bugfixes/github/test_issue_ghsa_h9x9_4f77_336w.py
Labels: bug, forward-to-main

#1745 fix: avoid processing MOV (quicktime) files when BMFF is enabled
  src/bmffimage.cpp
Labels: bug, enhancement, forward-to-main

#1718 Fix building for ios
  src/futils.cpp
Labels: platforms

#1739 Fix assertion failure in crwimage_int.cpp
  src/crwimage_int.cpp
  test/data/test_issue_ghsa_mv9g_fxh2_m49m.crw
  tests/bugfixes/github/test_issue_ghsa_mv9g_fxh2_m49m.py
Labels: bug, forward-to-main

#1773 Add fuzz target
  .github/workflows/on_PR_linux_fuzz.yml
  CMakeLists.txt
  README.md
  cmake/compilerFlags.cmake
  cmake/printSummary.cmake
  fuzz/CMakeLists.txt
  fuzz/fuzz-read-print-write.cpp
  src/iptc.cpp
  src/jpgimage.cpp
  src/tiffvisitor_int.cpp
Labels: build, enhancement

#1778 Fix infinite loop in Image::printIFDStructure
  src/image.cpp
  test/data/issue_ghsa_m479_7frc_gqqg_poc.crw
  tests/bugfixes/github/test_issue_ghsa_m479_7frc_gqqg.py
Labels: bug, forward-to-main

#1769 Safer std::vector indexing
  samples/addmoddel.cpp
  samples/exiv2json.cpp
  src/actions.cpp
  src/basicio.cpp
  src/convert.cpp
  src/exiv2.cpp
  src/minoltamn_int.cpp
  src/properties.cpp
  src/sigmamn_int.cpp
  src/tags_int.cpp
  src/tiffvisitor_int.cpp
  src/types.cpp
  src/utils.cpp
  src/value.cpp
  src/xmp.cpp
  src/xmpsidecar.cpp
  test/data/issue_ghsa_v5g7_46xf_h728_poc.exv
  tests/bugfixes/github/test_issue_ghsa_v5g7_46xf_h728.py
Labels: bug, forward-to-main

#1788 Make sure that read is complete to prevent infinite loop
  src/jpgimage.cpp
  test/data/issue_ghsa_9jh3_fcc3_g6hv_poc.jpg
  tests/bugfixes/github/test_issue_ghsa_9jh3_fcc3_g6hv.py
Labels: bug, forward-to-main

#1789 &bytes[0] (std::vector) will crash if bytes has zero elements
  src/image.cpp
  test/data/issue_ghsa_g44w_q3vm_gwjq_poc.jpg
  tests/bugfixes/github/test_issue_g44w_q3vm_gwjq.py
Labels: bug, forward-to-main

#1790 bufRead needs to be adjusted after seek()
  src/jpgimage.cpp
  test/data/icc-test.out
  test/data/issue_ghsa_mvc4_g5pv_4qqq_poc.jpg
  tests/bugfixes/github/test_issue_ghsa_9jh3_fcc3_g6hv.py
  tests/bugfixes/github/test_issue_ghsa_mvc4_g5pv_4qqq.py
  tests/bugfixes/redmine/test_issue_1247.py
Labels: bug, forward-to-main

#1803 refactor: small cleanup of test infra to avoid duplicate runs
  CMakeLists.txt
  tests/bash_tests/unit_test.py
  tests/bash_tests/version_test.py
Labels: testing
