Repository Exiv2/exiv2, pull requests merged in 2021-08, with the labels that each got.

#1816 Add bounds-check to prevent out-of-bounds read in memcmp
  src/jpgimage.cpp
  test/data/issue_1815_poc.jpg
  tests/bugfixes/github/test_issue_1815.py
Labels: bug, forward-to-main

#1818 Fix memory leak in pngimage.cpp
  src/pngimage.cpp
  test/data/issue_1817_poc.png
  tests/bugfixes/github/test_issue_1817.py
Labels: bug, forward-to-main

#1814 jp2image.cpp: check size before allocation to avoid out-of-memory errors
  src/jp2image.cpp
  test/data/issue_1812_poc.jp2
  tests/bugfixes/github/test_issue_1522.py
  tests/bugfixes/github/test_issue_1812.py
  tests/bugfixes/github/test_issue_ghsa_7569_phvm_vwc2.py
Labels: bug, forward-to-main

#1820 Check that the string isn't empty
  src/value.cpp
  test/data/issue_1819_poc.exv
  tests/bugfixes/github/test_issue_1819.py
  tests/bugfixes/github/test_issue_ghsa_v5g7_46xf_h728.py
Labels: bug, forward-to-main

#1828 Check value is in range before casting from double to uint32_t
  src/tags_int.cpp
  test/data/issue_1827_poc.crw
  tests/bugfixes/github/test_issue_1827.py
Labels: bug, forward-to-main

#1834 Replace assertion with an error message
  src/tiffcomposite_int.cpp
  test/data/issue_1833_poc.jpg
  tests/bugfixes/github/test_issue_1833.py
Labels: bug, forward-to-main

#1831 Safer casting from double to long in value.hpp
  include/exiv2/value.hpp
  test/data/issue_1830_poc.tiff
  tests/bugfixes/github/test_issue_1830.py
Labels: bug, forward-to-main

#1835 fix: incorrectly triggered enforce check during preview extraction
  src/preview.cpp
Labels: bug

#1796 Check if embedded RAF image is really a TIFF
  src/rafimage.cpp
  test/data/issue_1791_new.raf
  test/data/issue_1791_old.raf
  tests/bugfixes/github/test_issue_1791.py
Labels: bug, forward-to-main

#1850 Add test for issue 1821
  test/data/issue_1821_poc.xmp
  tests/bugfixes/github/test_issue_1821.py
Labels: forward-to-main

#1861 Add doc to release workflow
  .github/workflows/release.yml
Labels: forward-to-main

#1863 workaround for softprops/action-gh-release#139
  .github/workflows/release.yml
Labels: bug, CI

#1864 workaround for softprops/action-gh-release#139
  .github/workflows/release.yml
Labels: bug, CI
