Repository Exiv2/exiv2, pull requests merged in 2021-06, with the labels that each got.

#1690 fix: prevent creation of nightly release with draf==true
  .github/workflows/release.yml
Labels: CI

#1691 correct identification for Tamron SP 24-70mm G2 A032
  src/nikonmn_int.cpp
  test/data/Tamron_SP_24-70mm_F2.8_Di_VC_USD_G2_0E.exv
  tests/bugfixes/github/test_pr_1691.py
Labels: lens, makerNote

#1725 add lens: Olympus M.ZUIKO DIGITAL ED 12-45mm F4.0 PRO
  src/olympusmn_int.cpp
  test/data/olympus-m.zuiko-12-45mm-f4-pro.exv
  tests/bugfixes/github/test_issue_1723.py
Labels: lens

#1692 New Canon Lens Identification + Automatic Test of all Lenses
  src/canonmn_int.cpp
  src/tags_int.cpp
  test/data/exiv2-test.out
  test/data/template.exv
  tests/bugfixes/github/test_issue_45.py
  tests/bugfixes/redmine/test_issue_1166.py
  tests/bugfixes/redmine/test_issue_1170.py
  tests/bugfixes/redmine/test_issue_1252.py
  tests/lens_tests/__init__.py
  tests/lens_tests/test_canon_lenses.py
  tests/lens_tests/utils.py
  tests/system_tests.py
Labels: lens, makerNote, testing

#1722 Fix build with gtest 1.11
  unitTests/test_slice.cpp
Labels: testing

#1738 exifprint_lint
  README-SAMPLES.md
  README.md
  cmake/compilerFlags.cmake
  samples/exifprint.cpp
  tests/bugfixes/github/test_exifprint_lint.py
  tests/suite.conf
Labels: samples

#1735 Use vector::at() rather than operator[]
  include/exiv2/value.hpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/value.cpp
  test/data/issue_1706_poc.exv
  tests/bugfixes/github/test_issue_1706.py
Labels: forward-to-main

#1737 Zero initialize local variables.
  include/exiv2/types.hpp
  include/exiv2/value.hpp
  samples/Jzon.cpp
  samples/geotag.cpp
  samples/largeiptc-test.cpp
  samples/stringto-test.cpp
  samples/write-test.cpp
  src/actions.cpp
  src/bmffimage.cpp
  src/canonmn_int.cpp
  src/convert.cpp
  src/datasets.cpp
  src/http.cpp
  src/image.cpp
  src/pgfimage.cpp
  src/preview.cpp
  src/tags_int.cpp
  src/types.cpp
  src/value.cpp
  src/webpimage.cpp
  src/xmp.cpp
Labels: forward-to-main

#1720 Stricter date parsing in value.cpp
  src/value.cpp
  test/data/issue_1713_poc.xmp
  tests/bugfixes/github/test_issue_1713.py
Labels: forward-to-main

#1752 Fix incorrect loop condition
  src/jp2image.cpp
  test/data/issue_ghsa_mxw9_qx4c_6m8v_poc.jp2
  tests/bugfixes/github/test_issue_ghsa_8949_hhfh_j7rj.py
  tests/bugfixes/github/test_issue_ghsa_mxw9_qx4c_6m8v.py
Labels: forward-to-main
