Repository Exiv2/exiv2, pull requests merged in 2021-12, with the labels that each got.

#2000 Fix exiv2: verbose extract to stdout (see #1934)
  exiv2.md
  src/actions.cpp
  src/exiv2.cpp
  test/data/issue_1934_poc4-thumb_ref.jpg
  test/data/issue_1934_poc4.jpg
  test/data/issue_1934_poc4_comment_ref.txt
  test/data/issue_1934_poc4_ref.exv
  test/data/issue_1934_poc4_ref.icc
  tests/bugfixes/github/test_pr_2000.py
Labels: bug, samples

#2007 Fix integer overflow in PanasonicMakerNote::printAccelerometer
  src/panasonicmn_int.cpp
  test/data/issue_2006_poc.tiff
  tests/bugfixes/github/test_issue_2006.py
Labels: bug, OSS-Fuzz

#1547 fix_1416_iptc_DateCreated
  include/exiv2/value.hpp
  src/value.cpp
  tests/bash_tests/utils.py
  unitTests/test_DateValue.cpp
  unitTests/test_TimeValue.cpp
Labels: bug

#2037 Fix bug in loop. It wasn't iterating over the elements of dateStrings as intended
  samples/geotag.cpp
Labels: bug, forward-to-main

#2026 Add more DNG 1.6 tags
  src/tags_int.cpp
Labels: enhancement

#1970 Output of -PV was not suitable for inputting to -m-, key was missing.
  doc/cmdxmp.txt
  exiv2.md
  src/exiv2.cpp
  test/data/cmdxmp.txt
  tests/bugfixes/github/test_issue_1969.py
  tests/bugfixes/redmine/test_issue_1137.py
Labels: bug, samples
