Repository Exiv2/exiv2, pull requests merged in 2021-09, with the labels that each got.

#1888 Avoid reading 1 byte off the end when the string does not contain a '\0' byte
  src/crwimage_int.cpp
  test/data/issue_1887_poc.crw
  tests/bugfixes/github/test_issue_1887.py
Labels: bug, OSS-Fuzz

#1897 Lock conan version on Windows.
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_buils.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  .github/workflows/release.yml
Labels: forward-to-main

#1806 Call Metadatum::print() to increase fuzzing coverage.
  fuzz/fuzz-read-print-write.cpp
Labels: enhancement, testing

#1900 Remove unused constructor that was causing a build failure in OSS-Fuzz
  include/exiv2/value.hpp
Labels: OSS-Fuzz

#1872 Update exiv2 program and manpage
  man/man1/exiv2.1
  man/man1/exiv2.md
  src/exiv2.cpp
  test/data/exiv2-test.out
Labels: documentation, samples

#1910 Fix quadratic loops in pentaxmn_int.cpp
  src/pentaxmn_int.cpp
Labels: bug, OSS-Fuzz

#1902 Comment out bogus code in XMPUtils.cpp
  src/convert.cpp
  test/data/issue_1901_poc1.xmp
  test/data/issue_1901_poc2.xmp
  test/data/issue_1901_poc3.xmp
  test/data/issue_1901_poc4.xmp
  tests/bugfixes/github/test_issue_1901.py
  xmpsdk/src/XMPUtils.cpp
Labels: bug, OSS-Fuzz

#1915 Pass `-fstack-protector-strong` to linker
  cmake/compilerFlags.cmake
Labels: CMake, build

#1913 Fix integer overflow in print0x0007
  src/tags_int.cpp
  test/data/issue_1912_poc.jpg
  tests/bugfixes/github/test_issue_1912.py
Labels: bug

#1905 Update website docs
  doc/templates/Makefile
  doc/templates/tags-canon.html.in
  doc/templates/tags-nikon.html.in
  doc/templates/tags-samsung.html.in
  doc/templates/tags-sony.html.in
  src/tags.cpp
  tests/bugfixes/github/test_pr_1905.py
Labels: documentation, samples

#1922 Add SonyMisc(2b|3c) Groups for Sony TIFF files
  src/makernote_int.cpp
  tests/bugfixes/github/test_pr_1792.py
  tests/bugfixes/github/test_pr_1800.py
  tests/bugfixes/redmine/test_issue_1153.py
Labels: bug, makerNote

#1932 Update canonmn_int.cpp to correct lens "Canon EF 80-200mm f/4.5-5.6 II"
  src/canonmn_int.cpp
Labels: bug, lens, prettyPrinter

#1926 Add conditions to 2 Sony temperature tags
  src/sonymn_int.cpp
  src/sonymn_int.hpp
  tests/bugfixes/github/test_pr_1926.py
Labels: enhancement, makerNote, prettyPrinter

#1925 fix out of range access, minor performance improvement (0.27-maintenance backport)
  src/tags_int.cpp
  test/data/issue_1918_poc1.jpg
  test/data/issue_1918_poc2.jpg
  test/data/issue_1918_poc3.jpg
  tests/bugfixes/github/test_issue_1918.py
Labels: bug
