Repository Exiv2/exiv2, pull requests merged in 2022-08, with the labels that each got.

#1949 add support for more fujifilm tags
  src/fujimn_int.cpp
  test/data/test_reference_files/FujiTagsDRangeAutoRating1.jpg.out
  test/data/test_reference_files/FujiTagsDRangeStrongRating3.jpg.out
  test/data/test_reference_files/FujiTagsDRangeWeakRating2.jpg.out
  test/data/test_reference_files/FujiTagsSTone-2HTone4.jpg.out
  test/data/test_reference_files/FujiTagsSTone0HTone0Rating4.jpg.out
  test/data/test_reference_files/FujiTagsSTone1HTone-1Rating5.jpg.out
  test/data/test_reference_files/FujiTagsSTone4HTone-2.jpg.out
  test/data/test_reference_files/exiv2-bug1179a.exv.out
  test/data/test_reference_files/exiv2-bug1179b.exv.out
  test/data/test_reference_files/exiv2-bug1179c.exv.out
  test/data/test_reference_files/exiv2-bug1179d.exv.out
  test/data/test_reference_files/exiv2-bug1179e.exv.out
  test/data/test_reference_files/exiv2-bug1179f.exv.out
  test/data/test_reference_files/exiv2-bug1179g.exv.out
  test/data/test_reference_files/exiv2-bug1179h.exv.out
  test/data/test_reference_files/exiv2-bug1179i.exv.out
  test/data/test_reference_files/exiv2-bug1179j.exv.out
  test/data/test_reference_files/exiv2-fujifilm-finepix-s2pro.jpg.out
  test/data/test_reference_files/exiv2-pr1409.exv.out
  test/data/test_reference_files/exiv2-test.out
  tests/bugfixes/github/test_pr_1409.py
  tests/bugfixes/redmine/test_issue_1179.py
Labels: enhancement, makerNote, prettyPrinter

#2328 Fix rename text in manpage (#2290)
  man/man1/exiv2.1
Labels: documentation

#2331 Add request for exiv2 version/source (bug report)
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: support

#2333 Add more MIME type mappings for TIFF-based raws
  src/tiffimage.cpp
Labels: enhancement

#2274 Update Nikon flash tags
  doc/templates/Makefile
  doc/templates/tags-nikon.html.in
  exiv2.md
  include/exiv2/tags.hpp
  src/makernote_int.cpp
  src/nikonmn_int.cpp
  src/nikonmn_int.hpp
  src/tags_int.cpp
  src/tiffimage_int.cpp
  test/data/exiv2-issue1941-2.exv
  test/data/exiv2-issue1941-3.exv
  test/data/exiv2-issue1941-4.exv
  test/data/exiv2-issue1941-5.exv
  test/data/exiv2-issue1941-6_coverage.exv
  test/data/test_reference_files/CH0_0174.exv.out
  test/data/test_reference_files/Sigma_12-24mm_F4_DG_HSM_Art.exv.out
  test/data/test_reference_files/Sigma_120-300_DG_OS_HSM_Sport_lens.exv.out
  test/data/test_reference_files/Sigma_20mm_F1.4_DG_HSM_A.exv.out
  test/data/test_reference_files/Sigma_50mm_F1.4_DG_HSM_A.exv.out
  test/data/test_reference_files/Sigma_APO_MACRO_180_F3.5_EX_DG_HSM.exv.out
  test/data/test_reference_files/Stonehenge.exv.out
  test/data/test_reference_files/Tamron_SP70-300_F4-5.6_Di_VC_USD_A030.exv.out
  test/data/test_reference_files/Tamron_SP_24-70mm_F2.8_Di_VC_USD_G2_0E.exv.out
  test/data/test_reference_files/Tamron_SP_35mm_f1.4_Di_USD_F045.exv.out
  test/data/test_reference_files/Tokina_AT-X_14-20_F2_PRO_DX.exv.out
  test/data/test_reference_files/Tokina_ATX-i_11-20mm_F2.8_CF.exv.out
  test/data/test_reference_files/Tokina_atx-i_11-16mm_F2.8_CF.exv.out
  test/data/test_reference_files/_DSC8437.exv.out
  test/data/test_reference_files/exiv2-bug1014.exv.out
  test/data/test_reference_files/exiv2-bug1014_2.exv.out
  test/data/test_reference_files/exiv2-bug1026.jpg.out
  test/data/test_reference_files/exiv2-bug1062.jpg.out
  test/data/test_reference_files/exiv2-bug1108.exv.out
  test/data/test_reference_files/exiv2-bug1108.xmp.out
  test/data/test_reference_files/exiv2-bug1114.jpg.out
  test/data/test_reference_files/exiv2-bug1199.webp.out
  test/data/test_reference_files/exiv2-bug1348.exv.out
  test/data/test_reference_files/exiv2-bug922a.jpg.out
  test/data/test_reference_files/exiv2-issue1208.exv.out
  test/data/test_reference_files/exiv2-issue1941-1.exv.out
  test/data/test_reference_files/exiv2-issue1941-2.exv.out
  test/data/test_reference_files/exiv2-issue1941-3.exv.out
  test/data/test_reference_files/exiv2-issue1941-4.exv.out
  test/data/test_reference_files/exiv2-issue1941-5.exv.out
  test/data/test_reference_files/exiv2-issue1941-6_coverage.exv.out
  test/data/test_reference_files/exiv2-nikon-d70.jpg.out
  test/data/test_reference_files/exiv2-pr1105.exv.out
  test/data/test_reference_files/exiv2-test.out
  test/data/test_reference_files/issue_1934_poc1.exv.out
  test/data/test_reference_files/issue_743.exv.out
  test/data/test_reference_files/issue_ghsa_5p8g_9xf3_gfrr_poc.exv.out
  test/data/test_reference_files/issue_ghsa_5p8g_9xf3_gfrr_poc.webp.out
  test/data/test_reference_files/pr_1994_poc1.jpg.out
  test/data/test_reference_files/pr_1994_poc2.jpg.out
  test/data/test_reference_files/test_issue_990.exv.out
  tests/bugfixes/github/test_issue_1941.py
  tests/bugfixes/github/test_pr_1994.py
Labels: documentation, makerNote, prettyPrinter
