Repository Exiv2/exiv2, pull requests merged in 2022-10, with the labels that each got.

#2364 Fix/add exceptions for BMFF based files
  include/exiv2/bmffimage.hpp
  src/bmffimage.cpp
Labels: bug, imageHandler, architecture

#2378 Fix bugs in QuickTimeVideo::userDataDecoder
  src/quicktimevideo.cpp
  test/data/issue_2376_poc.mp4
  test/data/issue_2377_poc.mp4
  tests/bugfixes/github/test_issue_2376.py
  tests/bugfixes/github/test_issue_2377.py
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz

#2375 Fix bmff exception; Bump Conan version
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_buils.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  src/bmffimage.cpp
Labels: bug, architecture

#2382 Exif start can be at any byte in payload, not word aligned
  src/bmffimage.cpp
Labels: bug, imageHandler

#2374 several keys added to easyaccess
  README-SAMPLES.md
  samples/easyaccess-test.cpp
  src/easyaccess.cpp
  test/data/KonicaMinoltaDYNAX5D.exv
  test/data/NikonD1.exv
  test/data/SonyDSLR-A100.exv
  test/data/test_reference_files/KonicaMinoltaDYNAX5D.exv.out
  test/data/test_reference_files/NikonD1.exv.out
  test/data/test_reference_files/SonyDSLR-A100.exv.out
  tests/bash_tests/test_easyaccess.py
Labels: enhancement, samples

#2384 Avoid null pointer deref
  src/quicktimevideo.cpp
  test/data/issue_2383_poc.mp4
  tests/bugfixes/github/test_issue_2383.py
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz

#2389 Update makernote model ID tags
  src/canonmn_int.cpp
  src/pentaxmn_int.cpp
  src/sonymn_int.cpp
Labels: makerNote, good first issue

#2381 Support brotli compressed boxes in JPEG XL
  .github/workflows/codeql-analysis.yml
  .github/workflows/on_PR_windows_matrix.yml
  CMakeLists.txt
  README.md
  ci/install_dependencies.sh
  cmake/FindBrotli.cmake
  cmake/config.h.cmake
  cmake/findDependencies.cmake
  cmake/generateConfigFile.cmake
  cmake/printSummary.cmake
  conanfile.py
  include/exiv2/bmffimage.hpp
  src/CMakeLists.txt
  src/bmffimage.cpp
  src/version.cpp
Labels: enhancement, CI, imageHandler

#2216 Add more Canon RF lenses
  src/canonmn_int.cpp
  test/data/pr_2216.exv
  test/data/test_reference_files/pr_2216.exv.out
Labels: lens, makerNote

#2394 stop looping when eof is hit
  src/quicktimevideo.cpp
  test/data/issue_2393_poc.mp4
  tests/bugfixes/github/test_issue_2393.py
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz
