Repository Exiv2/exiv2, pull requests merged in 2022-03, with the labels that each got.

#2113 Add tag website build text to README.md
  README.md
  doc/templates/Makefile
Labels: documentation

#2139 Strip XMP raw packet before decoding (backport #2133)
  src/xmp.cpp
Labels: bug

#2142 Update CI actions (0.27-maintenance)
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly_Linux_distributions.yml
  .github/workflows/on_PR_linux_fuzz.yml
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_buils.yml
  .github/workflows/on_PR_mac_matrix.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  .github/workflows/release.yml
Labels: CI

#2145 More migration to size_t
  app/actions.cpp
  app/actions.hpp
  include/exiv2/cr2image.hpp
  include/exiv2/crwimage.hpp
  include/exiv2/exif.hpp
  include/exiv2/futils.hpp
  include/exiv2/image.hpp
  include/exiv2/iptc.hpp
  include/exiv2/metadatum.hpp
  include/exiv2/orfimage.hpp
  include/exiv2/pgfimage.hpp
  include/exiv2/preview.hpp
  include/exiv2/rw2image.hpp
  include/exiv2/tiffimage.hpp
  include/exiv2/value.hpp
  include/exiv2/xmp_exiv2.hpp
  src/basicio.cpp
  src/convert.cpp
  src/cr2header_int.cpp
  src/cr2header_int.hpp
  src/cr2image.cpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/crwimage_int.hpp
  src/exif.cpp
  src/futils.cpp
  src/image.cpp
  src/iptc.cpp
  src/jp2image.cpp
  src/jpgimage.cpp
  src/makernote_int.cpp
  src/makernote_int.hpp
  src/metadatum.cpp
  src/olympusmn_int.cpp
  src/orfimage.cpp
  src/orfimage_int.cpp
  src/orfimage_int.hpp
  src/pgfimage.cpp
  src/pngchunk_int.cpp
  src/pngimage.cpp
  src/preview.cpp
  src/psdimage.cpp
  src/rafimage.cpp
  src/rw2image.cpp
  src/sonymn_int.cpp
  src/sonymn_int.hpp
  src/tiffcomposite_int.cpp
  src/tiffcomposite_int.hpp
  src/tiffimage.cpp
  src/tiffimage_int.cpp
  src/tiffimage_int.hpp
  src/tiffvisitor_int.cpp
  src/tiffvisitor_int.hpp
  src/types.cpp
  src/value.cpp
  src/xmp.cpp
Labels: refactoring

#2161 Use std::round() in float_to_integer_helper
  include/exiv2/value.hpp
  test/data/issue_2160_poc.jpg
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz

#2171 also run clang-format check action on pull request
  .github/workflows/on_push_clang_format.yml
Labels: CI

#2167 Initial support for OM System MakerNote
  src/makernote_int.cpp
  src/makernote_int.hpp
  test/data/test_issue_2126.exv
  tests/bugfixes/github/test_issue_2126.py
Labels: enhancement, makerNote
