Repository Exiv2/exiv2, pull requests merged in 2022-02, with the labels that each got.

#2058 Fix pr#2053 for native Windows builds
  tests/bugfixes/github/test_issue_1959.py
  tests/bugfixes/github/test_pr_1979.py
  tests/bugfixes/github/test_pr_2000.py
Labels: bug, platforms, testing

#2068 Fix `exiv2`: verbose extract stdout mutli-file
  exiv2.md
  src/exiv2.cpp
  tests/bugfixes/github/test_pr_2068.py
Labels: bug, samples

#2063 Modernise code around iterators & smart pointers
  include/exiv2/types.hpp
  include/exiv2/value.hpp
  src/actions.cpp
  src/actions.hpp
  src/bmffimage.cpp
  src/bmpimage.cpp
  src/convert.cpp
  src/cr2image.cpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/epsimage.cpp
  src/exif.cpp
  src/exiv2.cpp
  src/gifimage.cpp
  src/image.cpp
  src/iptc.cpp
  src/jp2image.cpp
  src/jpgimage.cpp
  src/mrwimage.cpp
  src/orfimage.cpp
  src/pentaxmn_int.cpp
  src/pgfimage.cpp
  src/pngimage.cpp
  src/preview.cpp
  src/properties.cpp
  src/psdimage.cpp
  src/rafimage.cpp
  src/rw2image.cpp
  src/tgaimage.cpp
  src/tiffcomposite_int.cpp
  src/tiffcomposite_int.hpp
  src/tiffimage.cpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  src/value.cpp
  src/webpimage.cpp
  src/xmp.cpp
  src/xmpsidecar.cpp
  unitTests/test_XmpKey.cpp
  unitTests/test_slice.cpp
Labels: refactoring

#2076 Update markdown documentation
  README.md
  tests/README-TESTS.md
Labels: documentation

#2073 [nikon] Add Tokina AT-X 14-20 F2 PRO DX lens
  src/nikonmn_int.cpp
  test/data/Tokina_AT-X_14-20_F2_PRO_DX.exv
  tests/bugfixes/github/test_pr_2073.py
Labels: lens

#2072 [nikon] Add Tokina ATX-i 11-20mm F2.8 CF lens
  src/nikonmn_int.cpp
  test/data/Tokina_ATX-i_11-20mm_F2.8_CF.exv
  tests/bugfixes/github/test_pr_2072.py
Labels: lens

#2085 ci-conan: be more explicit about desired compiler in conan profile
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_builds.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
Labels: Conan

#2062 Replace Value::toLong with Value::toInt64.
  include/exiv2/types.hpp
  include/exiv2/value.hpp
  samples/stringto-test.cpp
  samples/xmpsample.cpp
  src/actions.cpp
  src/canonmn_int.cpp
  src/canonmn_int.hpp
  src/casiomn_int.cpp
  src/crwimage_int.cpp
  src/easyaccess.cpp
  src/exif.cpp
  src/iptc.cpp
  src/makernote_int.cpp
  src/minoltamn_int.cpp
  src/nikonmn_int.cpp
  src/olympusmn_int.cpp
  src/panasonicmn_int.cpp
  src/pentaxmn_int.cpp
  src/pentaxmn_int.hpp
  src/preview.cpp
  src/properties.cpp
  src/samsungmn_int.cpp
  src/sonymn_int.cpp
  src/tags_int.cpp
  src/tags_int.hpp
  src/tiffcomposite_int.cpp
  src/tiffcomposite_int.hpp
  src/tiffimage_int.cpp
  src/tiffvisitor_int.cpp
  src/types.cpp
  src/value.cpp
  src/xmp.cpp
Labels: refactoring

#2092 ci: remove conanCache from release workflow. Use newer python
  .github/workflows/release.yml
Labels: CI

#2094 fix(testing): fix codecov.yml
  .github/workflows/on_PR_linux_special_builds.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  codecov.yml
Labels: CI, testing

#2090 Get argv from main entry point encoded as UTF-8
  .github/workflows/nightly_Linux_distributions.yml
  .github/workflows/on_PR_linux_fuzz.yml
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_builds.yml
  .github/workflows/on_PR_mac_matrix.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  CMakeLists.txt
  README.md
  cmake/compilerFlags.cmake
  cmake/config.h.cmake
  cmake/generateConfigFile.cmake
  cmake/printSummary.cmake
  cmake/toolchain/Ubuntu20_04_mingw-w64-x86_64.cmake
  include/exiv2/basicio.hpp
  include/exiv2/error.hpp
  include/exiv2/exif.hpp
  include/exiv2/futils.hpp
  include/exiv2/image.hpp
  include/exiv2/preview.hpp
  include/exiv2/types.hpp
  samples/CMakeLists.txt
  samples/exifprint.cpp
  samples/exiv2json.cpp
  samples/geotag.cpp
  samples/werror-test.cpp
  src/CMakeLists.txt
  src/actions.cpp
  src/basicio.cpp
  src/error.cpp
  src/exif.cpp
  src/exiv2.cpp
  src/futils.cpp
  src/image.cpp
  src/preview.cpp
  src/tags_int.cpp
  src/tgaimage.cpp
  src/types.cpp
  src/version.cpp
  src/wmain.c
  tests/bash_tests/test_issue_1996.py
Labels: bug, Compilers, windows

#2098 Remove PR-Status badges from README
  .github/workflows/cifuzz.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/on_PR_linux_fuzz.yml
  .github/workflows/on_PR_linux_matrix.yml
  .github/workflows/on_PR_linux_special_builds.yml
  .github/workflows/on_PR_mac_matrix.yml
  .github/workflows/on_PR_windows_matrix.yml
  .github/workflows/on_push_BasicWinLinMac.yml
  .github/workflows/on_push_ExtraJobsForMain.yml
  README.md
Labels: documentation, CI

#2099 Separate exiv2 app source files from exiv2lib src folder
  CMakeLists.txt
  app/CMakeLists.txt
  app/actions.cpp
  app/actions.hpp
  app/app_utils.cpp
  app/app_utils.hpp
  app/exiv2.cpp
  app/exiv2app.hpp
  app/getopt.cpp
  app/getopt.hpp
  app/wmain.c
  samples/CMakeLists.txt
  samples/path-test.cpp
  src/CMakeLists.txt
  src/epsimage.cpp
  src/ini.cpp
  src/makernote_int.cpp
  src/sonymn_int.cpp
  src/utils.cpp
  src/utils.hpp
  test/data/test_reference_files/exiv2-test.out
  unitTests/CMakeLists.txt
Labels: refactoring, architecture

#2107 Replace Metadatum::toLong() with Metadatum::toInt64().
  include/exiv2/bmffimage.hpp
  include/exiv2/cr2image.hpp
  include/exiv2/crwimage.hpp
  include/exiv2/exif.hpp
  include/exiv2/image.hpp
  include/exiv2/iptc.hpp
  include/exiv2/metadatum.hpp
  include/exiv2/mrwimage.hpp
  include/exiv2/orfimage.hpp
  include/exiv2/pgfimage.hpp
  include/exiv2/rafimage.hpp
  include/exiv2/rw2image.hpp
  include/exiv2/tiffimage.hpp
  include/exiv2/xmp_exiv2.hpp
  samples/xmpsample.cpp
  src/bmffimage.cpp
  src/convert.cpp
  src/cr2image.cpp
  src/crwimage.cpp
  src/crwimage_int.cpp
  src/exif.cpp
  src/image.cpp
  src/iptc.cpp
  src/metadatum.cpp
  src/mrwimage.cpp
  src/nikonmn_int.cpp
  src/orfimage.cpp
  src/pentaxmn_int.cpp
  src/pgfimage.cpp
  src/pngchunk_int.cpp
  src/pngchunk_int.hpp
  src/preview.cpp
  src/rafimage.cpp
  src/rw2image.cpp
  src/sonymn_int.cpp
  src/tiffimage.cpp
  src/tiffvisitor_int.cpp
  src/xmp.cpp
Labels: refactoring

#2112 Fix test_pr_1905.py for native 2019msvc64 (#2108)
  test/data/test_reference_files/test_pr_1905_poc1_ref.out
  tests/bash_tests/test_pr_1905.py
  tests/suite.conf
Labels: testing, windows

#2111 Catch std::exception in iptcprint
  samples/iptcprint.cpp
Labels: bug

#2071 [nikon] Add instructions for adding new Nikon F mount lenses
  src/nikonmn_int.cpp
Labels: documentation, lens

#1919 fix for reading jpeg-xr images
  src/tiffimage_int.cpp
Labels: bug
