Repository Exiv2/exiv2, pull requests merged in 2022-11, with the labels that each got.

#2404 Update docs concerning BMFF-based files
  README.md
  man/man1/exiv2.1
Labels: documentation

#2405 Update README.md wrt BMFF
  README.md
Labels: documentation

#2420 Update `Exif.SonyMisc3c.*` and `Exif.Sony(1|2).SonyModelID`
  src/makernote_int.cpp
  src/sonymn_int.cpp
Labels: makerNote, prettyPrinter

#2412 Remove duplicate tag info entries fujifilm
  src/fujimn_int.cpp
  test/data/FujiFilmA850.exv
  test/data/FujiFilmFinePixF550EXR.exv
  test/data/FujiSLP800.exv
  test/data/test_reference_files/FujiFilmA850.exv.out
  test/data/test_reference_files/FujiFilmFinePixF550EXR.exv.out
  test/data/test_reference_files/FujiSLP800.exv.out
Labels: bug, makerNote, prettyPrinter

#2424 Fix long-running loop in QuickTimeVideo::sampleDesc
  include/exiv2/quicktimevideo.hpp
  src/quicktimevideo.cpp
  test/data/issue_2423_poc.mp4
  tests/bugfixes/github/test_issue_2423.py
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz

#2428 Fix memory leak in BmffImage::brotliUncompress
  src/bmffimage.cpp
  test/data/issue_2427_poc.jpg
  tests/bugfixes/github/test_issue_2427.py
  tests/regression_tests/test_regression_allfiles.py
Labels: bug, OSS-Fuzz
