Repository Exiv2/exiv2, pull requests merged in 2022-05, with the labels that each got.

#2239 Account for header bytes for Exif and XMP boxes (backport #2234)
  src/bmffimage.cpp
Labels: bug, imageHandler

#2215 Add some F mount lenses
  src/nikonmn_int.cpp
Labels: lens

#2244 More bounds checking in Adjust::adjustDateTime
  app/actions.cpp
Labels: refactoring
