Repository Exiv2/exiv2, pull requests merged in 2022-04, with the labels that each got.

#2192 [0.27] Detect integer-overflow and throw in that case
  src/exif.cpp
  test/data/issue_2190_poc.jp2
Labels: bug

#2197 Refactoring in JpegImage and Photoshop classes
  app/exiv2.cpp
  include/exiv2/exiv2.hpp
  include/exiv2/jpgimage.hpp
  include/exiv2/photoshop.hpp
  src/CMakeLists.txt
  src/image.cpp
  src/jpgimage.cpp
  src/photoshop.cpp
  src/pngchunk_int.cpp
  src/pngimage.cpp
  src/preview.cpp
  src/psdimage.cpp
  src/tiffvisitor_int.cpp
  tests/bugfixes/github/test_issue_1833.py
  tests/bugfixes/github/test_issue_1881.py
  tests/bugfixes/github/test_issue_756.py
  unitTests/test_Photoshop.cpp
Labels: enhancement, refactoring

#2203 Create da.po
  po/da.po
Labels: L10n

#2209 Improvements around TODO comments
  app/actions.cpp
  include/exiv2/types.hpp
  samples/addmoddel.cpp
  src/crwimage_int.cpp
  src/epsimage.cpp
  src/jpgimage.cpp
  src/pngchunk_int.cpp
  src/pngimage.cpp
  src/rafimage.cpp
  src/tiffcomposite_int.cpp
  src/types.cpp
  src/utils.cpp
  src/utils.hpp
  src/webpimage.cpp
  src/xmpsidecar.cpp
  tests/bugfixes/github/test_issue_960.py
  unitTests/CMakeLists.txt
  unitTests/test_types.cpp
  unitTests/test_utils.cpp
Labels: enhancement
