Repository Exiv2/exiv2, pull requests merged in 2022-07, with the labels that each got.

#2248 fix naming of canon EF 35-80mm. closes #2247
  src/canonmn_int.cpp
  test/data/20220610_MG_7237.exv
  test/data/20220610_MG_7238.exv
  test/data/20220610_MG_7239.exv
  test/data/20220610_MG_7240.exv
  test/data/20220610_MG_7241.exv
  test/data/test_reference_files/20220610_MG_7237.exv.out
  test/data/test_reference_files/20220610_MG_7238.exv.out
  test/data/test_reference_files/20220610_MG_7239.exv.out
  test/data/test_reference_files/20220610_MG_7240.exv.out
  test/data/test_reference_files/20220610_MG_7241.exv.out
Labels: lens

#2269 Replace assert with enforce
  src/jp2image.cpp
  test/data/issue_2268_poc.jp2
  tests/bugfixes/github/test_issue_2268.py
Labels: bug, forward-to-main

#2279 Add tag description option to exiv2 app
  app/actions.cpp
  app/exiv2.cpp
  app/exiv2app.hpp
  exiv2.md
  include/exiv2/datasets.hpp
  include/exiv2/exif.hpp
  include/exiv2/iptc.hpp
  include/exiv2/metadatum.hpp
  include/exiv2/properties.hpp
  include/exiv2/tags.hpp
  include/exiv2/xmp_exiv2.hpp
  src/datasets.cpp
  src/exif.cpp
  src/iptc.cpp
  src/properties.cpp
  src/xmp.cpp
  test/data/test_reference_files/exiv2-test.out
  tests/bash_tests/test_pr_2279.py
Labels: documentation, samples, architecture
