Repository Exiv2/exiv2, pull requests merged in 2023-11, with the labels that each got.

#2810 Add new Nikon Z lenses
  src/nikonmn_int.cpp
Labels: lens

#2816 Fix test failure on Mac
  tests/bugfixes/github/test_issue_2427.py
Labels: forward-to-main

#2809 easy access: Tag sequence changed for serialNumber and lensName
  src/easyaccess.cpp
Labels: makerNote

#2819 install exiv2 cmake module in LIBDIR
  src/CMakeLists.txt
Labels: CMake

#2824 RAF: extract more details when printing structure
  src/rafimage.cpp
Labels: imageHandler

#2839 Add more Canon RF lenses
  src/canonmn_int.cpp
Labels: lens

#2842 Add support for HTJ2K mime type
  include/exiv2/jp2image.hpp
  src/jp2image.cpp
  src/jp2image_int.cpp
  src/jp2image_int.hpp
Labels: imageHandler

#2830 RAF: get actual sensor dimensions
  src/rafimage.cpp
Labels: imageHandler
