Repository Exiv2/exiv2, pull requests merged in 2023-05, with the labels that each got.

#2612 BMFF: fix handling of boxes w/ zero length or type
  src/bmffimage.cpp
  test/data/pr_2612_poc.heic
  test/data/test_reference_files/pr_2612_poc.heic.out
Labels: bug, imageHandler

#2614 BMFF: fix handling of boxes w/ zero length or type (backport #2612)
  src/bmffimage.cpp
Labels: bug, imageHandler

#2626 Adapt for NetBSD iconv() prototype change
  cmake/config.h.cmake
Labels: platforms

#2625 Fix build on NetBSD.
  src/futils.cpp
Labels: platforms

#2613 Extract XMP data from embedded JPEG preview inside RAF files
  src/rafimage.cpp
  tests/bugfixes/github/test_issue_857.py
Labels: enhancement, imageHandler
