Repository Exiv2/exiv2, pull requests merged in 2023-09, with the labels that each got.

#2755 Add new Sony camera IDs (backport #2747)
  src/sonymn_int.cpp
Labels: makerNote

#2765 Fix MSVC Conan profile
  cmake/msvc_conan_profiles/msvc2019Release64
Labels: build

#2760 Nikon printApertureLd4 translate value 0 to n/a
  src/nikonmn_int.cpp
  test/data/NikonZ6.exv
  test/data/test_reference_files/CH0_0174.exv.out
  test/data/test_reference_files/NikonZ6.exv.out
  tests/bash_tests/test_easyaccess.py
  tests/bugfixes/github/test_pr_1437.py
Labels: lens, makerNote

#2771 Fix WebP ICCP chunk header
  src/webpimage.cpp
Labels: imageHandler

#2749 Add basic DNG 1.7 tag support
  src/tags_int.cpp
  test/data/test_reference_files/IMG_1361.dng.out
  test/data/test_reference_files/test_pr_1905_poc1_ref.out
  tests/bugfixes/github/test_pr_1436.py
Labels: enhancement
