Repository Exiv2/exiv2, pull requests merged in 2023-03, with the labels that each got.

#2543 Convert tail-recursion to loop to avoid stack exhaustion
  src/riffvideo.cpp
Labels: bug, OSS-Fuzz

#2544 Check that the pointer isn't NULL
  src/matroskavideo.cpp
Labels: bug, OSS-Fuzz

#2558 Explicitly include stdint
  include/exiv2/types.hpp
Labels: bug, Compilers

#2568 Add some more Nikon Z lenses
  src/nikonmn_int.cpp
Labels: lens

#2567 makernotes: workaround for Olympus header corruption
  src/makernote_int.cpp
Labels: makerNote
